### ISSUE TITLE
dmidiplayer.exe v1.6.0 and later runs only in Windows 10 or later

### ISSUE THREAD

**Issue by hellishvictor** [pedrolcl/dmidiplayer#12]
Hi, it seems that [dmidiplayer](https://sourceforge.net/projects/dmidiplayer/files/v1.7.2/) doesn't work with Win 7 SP1 x64.
Everything went well with installation, but at launch the program it shows:
![_sshot-1](https://github.com/pedrolcl/dmidiplayer/assets/34694956/3513b38d-7532-48f1-96df-08e79fc0250f)

Cheers.

**Comment by pedrolcl** [comment]
No, it won't work on Windows 7 because version 1.7.2 is compiled with Qt 6.5.1 and Qt 6.5 supports only Windows 10 and later: https://doc.qt.io/qt-6/supported-platforms.html

You may try [v1.5.3](https://sourceforge.net/projects/dmidiplayer/files/v1.5.3/) or an older release.

**Comment by hellishvictor** [comment]
Yeah, v1.5.3 did work, thank you :)
I hope that in the latest releases there's not that splash screen.
Cheers.
