### ISSUE TITLE
ability to load several soundfonts

### ISSUE THREAD

**Issue by pedrolcl** [pedrolcl/dmidiplayer#19]
Pedro - got it. Thanks for the timely response. And thanks for this app.

If you are looking for enhancement suggestions - the ability to load several soundfonts would be great as I have a few different ones for different instruments; and sometimes I have MIDI files where I want to use different .sf2 files for different parts (MIDI tracks).

But again, thanks for helping with my question.

_Originally posted by @JeffRocchio in https://github.com/pedrolcl/dmidiplayer/discussions/18#discussioncomment-9848068_

**Comment by JeffRocchio** [comment]
Works perfectly - Thank you!
