### ISSUE TITLE
The Help is blank in Windows 10-64:

### ISSUE THREAD

**Issue by pedrolcl** [pedrolcl/dmidiplayer#7]
The Help is blank in Windows 10-64:
![drumstick-help](https://user-images.githubusercontent.com/42104122/233207299-92accd2b-a957-438a-b388-dd02fabefd7c.png)

_Originally posted by @practicafz in https://github.com/pedrolcl/dmidiplayer/discussions/3#discussioncomment-5666898_

**Comment by pedrolcl** [comment]
There is a bug in the default language detection, and when saving the setting on the registry.

The workaround is to change the language: Help->Language. Choose another, and then switch back to English.

**Comment by practicafz** [comment]
Great, that works!

**Comment by pedrolcl** [comment]
This issue was fixed in commit 000dda4a791536315d91d2f43d01941a58f59e62
